### ISSUE TITLE
Storing the image as cache? 

### ISSUE THREAD

**Issue by Vir-al** [mthahzan/react-native-image-fallback#16]
I've implemented it in my application and everything is working fine (Running on Android). But my application cache size increasing every time I load new images. Therefore, my question is, Does the library store the images in the cache? 

If yes, what will be the path of the images to access or clear the cache over time?

There is no information in ReadMe about this, Kindly help.

**Comment by mikehardy** [comment]
You may access the code, yes? It is uncomplicated and not many lines - your fastest resolution will be your own code inspection

**Comment by mthahzan** [comment]
@Vir-al this library uses React Native Image component by default (you may provide your own component) and is simply a proxy layer to handle the fallback logic. The caching is handled entirely by the actual image components themselves. You might wanna read up on [React Native Image](https://reactnative.dev/docs/image#source) (or the custom component you may be using)

**Comment by Vir-al** [comment]
@mthahzan Thank you for the response. Understood the working.
