### ISSUE TITLE
Remove deprecated lifecycle hooks

### ISSUE THREAD

**Issue by mthahzan** [mthahzan/react-native-image-fallback#3]
`componentWillReceiveProps is deprecated since React 16.3.`. Update the code to fix this issue that will break in the next major version.

**Comment by mikehardy** [comment]
Hey @mthahzan - I'm using this and it seems to work but it does need a bit of a refresh, including this issue. Are you open to collaborate on this? I can propose some PRs to fix the issues. I'll be developing them locally to use with patch-package at minimum, would be great to get them upstream here.

**Comment by mthahzan** [comment]
@mikehardy yes please, PRs are more than welcome. I'm a little short on time to maintain this properly.
