### ISSUE TITLE
Image not updating correctly when props change

### ISSUE THREAD

**Issue by mikehardy** [mthahzan/react-native-image-fallback#9]
Hello again after quite a long time @mthahzan  :-)

I've been updating my dependencies and I'm not sure exactly what changed, but I noticed today that under certain circumstances, you could change the source/fallback props but the internal state of this component would not update the sources list, so the image would not change

When I traced it out, it seemed that there were a couple problems:

- The [original source/fallback are not cached in state](https://github.com/mthahzan/react-native-image-fallback/blob/23c260e94e8327df5ade44e589ddaa08d31ad6b5/src/components/ImageLoader.js#L76-L82), so [the test in getDerivedStateFromProps](https://github.com/mthahzan/react-native-image-fallback/blob/23c260e94e8327df5ade44e589ddaa08d31ad6b5/src/components/ImageLoader.js#L97) will always fail, meaning it never updates!
- If you fix that, the getAllImageSources is called correctly but under certain conditions after the class instance is destroyed (['This method doesn’t have access to the component instance'](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops))

I have fixes for this so that it seems to be working well (again? I don't recall it failing prior to updates, but whatever) if you'd like a PR?

I'll probably post the PR and a patch-package patch either way in case it's useful to others

**Comment by mthahzan** [comment]
Hello again @mikehardy. Thanks for the PR. Not sure how it broke though. Maybe some ReactJS internals changed? I dunno.

I'll publish the update ASAP

**Comment by mikehardy** [comment]
Could be, I'm in the process of adopting react 17. When I look at it I'm not sure how it worked before but it did! This way appears more correct to me visually and works with current stable everything at least. Never a dull moment with software 😅. Thanks for the merge!

**Comment by mikehardy** [comment]
Hey @mthahzan - consider this a friendly pester for a 1.0.1 release with my merged PR :-)
Cheers

**Comment by mthahzan** [comment]
My apologies @mikehardy. Caught the virus and forgot all about this. v1.0.1 published

**Comment by mthahzan** [comment]
Thanks for the concern Mike. Thankfully I don't have any raspatory problems so the effects are quite minimal. I'm pretty much 100% back now
